### ISSUE TITLE
Rabbits doesnt spawn!

### ISSUE THREAD

**Issue by Oyasumei** [AlexModGuy/AlexsMobs#118]
So Im playing on my own modpack, and figured out that after adding Alexs mobs rabbits doesnt spawn anymore. Any fix plox? :(

**Comment by VastayanWings** [comment]
together with alexmobs comes a mod called citadel
change in the citadel config the "chunkGenSpawnModifier" from 1.0 to 2.0 (or higher depending on u other mobspawning mods)
this should spawn rabbits again tho they will still be rare (specially since alot of mobs tend to kill them like snakes in deserts)
