### ISSUE TITLE
CME on game startup

### ISSUE THREAD

**Issue by Vazkii** [AlexModGuy/AlexsMobs#137]
https://gist.github.com/Vazkii/bc99157fa924a242921342f4f638d504

**Comment by AbsorbingSafe11** [comment]
Sorry for asking any stupid questions (or otherwise not knowing what I am talking about), but did you try loading the pack without Upstream and Charm? (Charmonium also)
I ask because I have had a bunch of issues with both mods, more so with Upstream. (charm 2.1.9 works fine)
Upstream may cause the issue as the crocodile from Alex's mobs may have attempted to spawn in Upstream's "river" biome.
To test could you possibly load a world in a single biome world without rivers?
(also sorry if issue was fixed or solution to problem became obsolete)

**Comment by AlexModGuy** [comment]
fixed
