### ISSUE TITLE
Crimson Mosquito and modded biome

### ISSUE THREAD

**Issue by RUsami** [AlexModGuy/AlexsMobs#189]
Hello,

I have a problem with the Crimson Mosquito mob with modded biome (BOP,BYG)
I modified the "crimson_mosquito_spawns.json" file to add a new biome to spawn in ("byg:crimson_gardens") but it only spawn in the original "minecraft:crimson_forest"
While in "minecraft:crimson_forest" the command /kill @e[type=alexsmobs:crimson_mosquito] successfully kill multiple entities
While in "byg:crimson_gardens" the command /kill @e[type=alexsmobs:crimson_mosquito] give "No entity was found"
Tested with many worlds, and spawnweight

here the modified json code, maybe I did something wrong with the code ? Is there a fix I can apply ? Is there a gameplay feature I'm missing ?

Thanks in advance for any help

`{
  "biomes": [
    [
      {
        "type": "REGISTRY_NAME",
        "negate": false,
        "value": "minecraft:crimson_forest"
      }
    ],
    [
      {
        "type": "REGISTRY_NAME",
        "negate": false,
        "value": "byg:crimson_gardens"
      }
    ]
  ]
}`

**Comment by Alex-the-666** [comment]
crimson mosquitoes can only spawn on blocks under crimson_mosquito_spawns.json in our internal datapack.. maybe issue is there

**Comment by NJL5390** [comment]
> crimson mosquitoes can only spawn on blocks under crimson_mosquito_spawns.json in our internal datapack.. maybe issue is there

Yeah, I'm getting this issue in relation to biomes o plenty nether biomes, when I've tried adding the visceral heap to the spawn biomes for the crimson mosquito they don't spawn because they can't spawn on the flesh blocks that the biome is made from, due to those blocks not being a part of that tag:
![2021-02-23_18 13 07](https://user-images.githubusercontent.com/64381954/108888562-88fa0c00-7603-11eb-89ce-92a5ab0b49f6.png)
![2021-02-23_18 11 50](https://user-images.githubusercontent.com/64381954/108888749-9dd69f80-7603-11eb-9125-10c73b056d77.png)
The same thing also happens when trying to add Soul vultures to the withered abyss, the config is functional but the mob can't spawn due to the entire biome being made of blackstone and obsidian which aren't listed as spawnable blocks for the mob.
